import type { DB_CategoryInsertType } from "~/server/db/schema/categories";

export const DEFAULT_CATEGORIES: Omit<
  DB_CategoryInsertType,
  "organizationId"
>[] = [
  // Income categories
  {
    slug: "stipendio",
    name: "Stipendio",
    type: "income",
    color: "oklch(52.7% 0.154 150.069)",
    icon: "badge-dollar-sign",
    description: "Reddito da lavoro dipendente.",
  },
  {
    slug: "bonus-premi",
    name: "Bonus / Premi",
    type: "income",
    color: "oklch(50.8% 0.118 165.612)",
    icon: "star",
    description: "Bonus, premi o incentivi.",
  },
  {
    slug: "altro-reddito",
    name: "Altro reddito",
    type: "income",
    color: "oklch(51.1% 0.096 186.391)",
    icon: "plus-circle",
    description: "Altre fonti di reddito.",
  },

  // Expense categories
  {
    slug: "casa",
    name: "Casa",
    type: "expense",
    color: "oklch(50.5% 0.213 27.518)",
    icon: "home",
    description: "Spese generali per la casa.",
  },
  {
    slug: "affitto-mutuo",
    name: "Affitto / Mutuo",
    type: "expense",
    color: "oklch(55.3% 0.195 38.402)",
    icon: "building-2",
    description: "Pagamento affitto o mutuo.",
  },
  {
    slug: "utenze",
    name: "Utenze (Luce, Gas, Internet)",
    type: "expense",
    color: "oklch(55.5% 0.163 48.998)",
    icon: "plug",
    description: "Bolletta luce, gas, internet, ecc.",
  },
  {
    slug: "trasporti",
    name: "Trasporti",
    type: "expense",
    color: "oklch(55.4% 0.135 66.442)",
    icon: "car",
    description: "Spese per spostamenti e trasporti.",
  },
  {
    slug: "spesa-cibo",
    name: "Spesa e cibo",
    type: "expense",
    color: "oklch(52.5% 0.223 3.958)",
    icon: "shopping-cart",
    description: "Spese alimentari e cibo.",
  },
  {
    slug: "ristoranti-bar",
    name: "Ristoranti & Bar",
    type: "expense",
    color: "oklch(51.4% 0.222 16.935)",
    icon: "utensils",
    description: "Pranzi, cene, bar e locali.",
  },
  {
    slug: "famiglia-persone",
    name: "Famiglia & Persone",
    type: "expense",
    color: "oklch(52% 0.105 223.128)",
    icon: "users",
    description: "Spese per famiglia e persone care.",
  },
  {
    slug: "salute",
    name: "Salute",
    type: "expense",
    color: "oklch(50% 0.134 242.749)",
    icon: "heart-pulse",
    description: "Spese mediche e salute.",
  },
  {
    slug: "tempo-libero",
    name: "Tempo libero",
    type: "expense",
    color: "oklch(51.8% 0.253 323.949)",
    icon: "gamepad-2",
    description: "Hobby, sport, attività ricreative.",
  },
  {
    slug: "viaggi",
    name: "Viaggi",
    type: "expense",
    color: "oklch(53.2% 0.157 131.589)",
    icon: "plane",
    description: "Vacanze e viaggi.",
  },
  {
    slug: "abbonamenti",
    name: "Abbonamenti (Netflix, Spotify, ecc.)",
    type: "expense",
    color: "oklch(37.2% 0.044 257.287)",
    icon: "credit-card",
    description: "Abbonamenti e servizi ricorrenti.",
  },

  // Transfer categories
  {
    slug: "risparmi",
    name: "Risparmi",
    type: "transfer",
    color: "oklch(48.8% 0.243 264.376)",
    icon: "piggy-bank",
    description: "Trasferimenti verso risparmi.",
  },
  {
    slug: "investimenti",
    name: "Investimenti",
    type: "transfer",
    color: "oklch(49.6% 0.265 301.924)",
    icon: "chart-candlestick",
    description: "Trasferimenti verso investimenti.",
  },
  {
    slug: "transfers",
    name: "Giroconti",
    type: "transfer",
    color: "oklch(37.4% 0.01 67.558)",
    icon: "chart-candlestick",
    description: "Trasferimenti interni.",
  },
] as const;
