import {
  ActivityIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  AwardIcon,
  BanknoteArrowUpIcon,
  BellIcon,
  Building2Icon,
  CarIcon,
  CatIcon,
  ChartCandlestickIcon,
  CheckSquareIcon,
  CigaretteIcon,
  CircleDashedIcon,
  CoffeeIcon,
  CreditCardIcon,
  DicesIcon,
  DogIcon,
  FuelIcon,
  Gamepad2Icon,
  HamburgerIcon,
  HandCoinsIcon,
  HeartIcon,
  HomeIcon,
  HousePlugIcon,
  LockIcon,
  MapIcon,
  PiggyBankIcon,
  PlaneIcon,
  RocketIcon,
  ShoppingCartIcon,
  SmartphoneIcon,
  SmileIcon,
  SparklesIcon,
  SproutIcon,
  TagIcon,
  ThumbsUpIcon,
  TvIcon,
  UmbrellaIcon,
  UsersIcon,
  UtensilsIcon,
} from "lucide-react";

// Define available icons with their lucide-react dashed-case names and Icon suffix
export const DEFAULT_ICONS = [
  { name: "circle-dashed", icon: CircleDashedIcon },
  { name: "coffee", icon: CoffeeIcon },
  { name: "cat", icon: CatIcon },
  { name: "dog", icon: DogIcon },
  { name: "heart", icon: HeartIcon },
  { name: "credit-card", icon: CreditCardIcon },
  { name: "piggy-bank", icon: PiggyBankIcon },
  { name: "bell", icon: BellIcon },
  { name: "sparkles", icon: SparklesIcon },
  { name: "cigarette", icon: CigaretteIcon },
  { name: "smile", icon: SmileIcon },
  { name: "arrow-left", icon: ArrowLeftIcon },
  { name: "activity", icon: ActivityIcon },
  { name: "hand-coins", icon: HandCoinsIcon },
  { name: "tag", icon: TagIcon },
  { name: "banknote-arrow-up", icon: BanknoteArrowUpIcon },
  { name: "rocket", icon: RocketIcon },
  { name: "lock", icon: LockIcon },
  { name: "thumbs-up", icon: ThumbsUpIcon },
  { name: "umbrella", icon: UmbrellaIcon },
  { name: "house-plug", icon: HousePlugIcon },
  { name: "fuel", icon: FuelIcon },
  { name: "check-square", icon: CheckSquareIcon },
  { name: "map", icon: MapIcon },
  { name: "smartphone", icon: SmartphoneIcon },
  { name: "tv", icon: TvIcon },
  { name: "gamepad-2", icon: Gamepad2Icon },
  { name: "sprout", icon: SproutIcon },
  { name: "users", icon: UsersIcon },
  { name: "shopping-cart", icon: ShoppingCartIcon },
  { name: "plane", icon: PlaneIcon },
  { name: "arrow-right", icon: ArrowRightIcon },
  { name: "utensils", icon: UtensilsIcon },
  { name: "building-2", icon: Building2Icon },
  { name: "home", icon: HomeIcon },
  { name: "hamburger", icon: HamburgerIcon },
  { name: "chart-candlestick", icon: ChartCandlestickIcon },
  { name: "dices", icon: DicesIcon },
  { name: "award", icon: AwardIcon },
  { name: "car", icon: CarIcon },
] as const;

export type IconKey = (typeof DEFAULT_ICONS)[number]["name"];
