import {
  AlertCircle,
  BanknoteArrowDown,
  BanknoteArrowUp,
  Calendar,
  Camera,
  Check,
  Clock,
  Database,
  Download,
  Edit,
  File,
  Folder,
  HandCoinsIcon,
  Heart,
  HelpCircle,
  Home,
  HouseIcon,
  ImageIcon,
  Info,
  Key,
  Lock,
  Mail,
  MapPin,
  Minus,
  Phone,
  Plus,
  Search,
  Settings,
  Shield,
  Star,
  Trash2,
  Unlock,
  Upload,
  User,
  X,
} from "lucide-react";

// Define available icons with their components and names
export const AVAILABLE_ICONS = {
  house: { name: "House", component: HouseIcon },
  user: { name: "User", component: User },
  settings: { name: "Settings", component: Settings },
  search: { name: "Search", component: Search },
  heart: { name: "Heart", component: Heart },
  star: { name: "Star", component: Star },
  lock: { name: "Lock", component: Lock },
  unlock: { name: "Unlock", component: Unlock },
  mail: { name: "Mail", component: Mail },
  phone: { name: "Phone", component: Phone },
  calendar: { name: "Calendar", component: Calendar },
  clock: { name: "Clock", component: Clock },
  mapPin: { name: "Map Pin", component: MapPin },
  camera: { name: "Camera", component: Camera },
  image: { name: "Image", component: ImageIcon },
  file: { name: "File", component: File },
  folder: { name: "Folder", component: Folder },
  download: { name: "Download", component: Download },
  upload: { name: "Upload", component: Upload },
  edit: { name: "Edit", component: Edit },
  trash: { name: "Trash", component: Trash2 },
  plus: { name: "Plus", component: Plus },
  minus: { name: "Minus", component: Minus },
  check: { name: "Check", component: Check },
  x: { name: "X", component: X },
  alert: { name: "Alert", component: AlertCircle },
  info: { name: "Info", component: Info },
  help: { name: "Help", component: HelpCircle },
  shield: { name: "Shield", component: Shield },
  key: { name: "Key", component: Key },
  database: { name: "Database", component: Database },
  "hand-coins": { name: "HandCoins", component: HandCoinsIcon },
  "banknote-arrow-up": { name: "BanknoteArrowUp", component: BanknoteArrowUp },
  "banknote-arrow-down": {
    name: "BanknoteArrowDown",
    component: BanknoteArrowDown,
  },
} as const;

export type IconKey = keyof typeof AVAILABLE_ICONS;
