import {
  ActivityIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  AwardIcon,
  BellIcon,
  CheckSquareIcon,
  CircleDashedIcon,
  CircleIcon,
  ClockIcon,
  CrosshairIcon,
  DiscIcon,
  EditIcon,
  HeartIcon,
  HomeIcon,
  KeyIcon,
  LightbulbIcon,
  LockIcon,
  MapIcon,
  MessageCircleIcon,
  MonitorIcon,
  PaletteIcon,
  PhoneIcon,
  RocketIcon,
  SettingsIcon,
  ShoppingCartIcon,
  SmartphoneIcon,
  SmileIcon,
  SparklesIcon,
  StarIcon,
  TagIcon,
  ThumbsUpIcon,
  TriangleIcon,
  TvIcon,
  UmbrellaIcon,
  UserIcon,
  Volume2Icon,
} from "lucide-react";

// Define available icons with their lucide-react dashed-case names and Icon suffix
export const DEFAULT_ICONS = [
  { name: "circle-dashed", icon: CircleDashedIcon },
  { name: "heart", icon: HeartIcon },
  { name: "star", icon: StarIcon },
  { name: "phone", icon: PhoneIcon },
  { name: "bell", icon: BellIcon },
  { name: "sparkles", icon: SparklesIcon },
  { name: "clock", icon: ClockIcon },
  { name: "smile", icon: SmileIcon },
  { name: "arrow-left", icon: ArrowLeftIcon },
  { name: "activity", icon: ActivityIcon },
  { name: "key", icon: KeyIcon },
  { name: "tag", icon: TagIcon },
  { name: "lightbulb", icon: LightbulbIcon },
  { name: "rocket", icon: RocketIcon },
  { name: "lock", icon: LockIcon },
  { name: "thumbs-up", icon: ThumbsUpIcon },
  { name: "umbrella", icon: UmbrellaIcon },
  { name: "edit", icon: EditIcon },
  { name: "settings", icon: SettingsIcon },
  { name: "check-square", icon: CheckSquareIcon },
  { name: "map", icon: MapIcon },
  { name: "smartphone", icon: SmartphoneIcon },
  { name: "tv", icon: TvIcon },
  { name: "triangle", icon: TriangleIcon },
  { name: "circle", icon: CircleIcon },
  { name: "monitor", icon: MonitorIcon },
  { name: "shopping-cart", icon: ShoppingCartIcon },
  { name: "user", icon: UserIcon },
  { name: "arrow-right", icon: ArrowRightIcon },
  { name: "volume-2", icon: Volume2Icon },
  { name: "crosshair", icon: CrosshairIcon },
  { name: "home", icon: HomeIcon },
  { name: "disc", icon: DiscIcon },
  { name: "palette", icon: PaletteIcon },
  { name: "message-circle", icon: MessageCircleIcon },
  { name: "award", icon: AwardIcon },
] as const;

export type IconKey = (typeof DEFAULT_ICONS)[number]["name"];
